### ISSUE TITLE
Oreo Support

### ISSUE THREAD

**Issue by DespairFactor** [neobuddy89/shamu#2]
What changes did you make to ensure that nougat source was working on oreo? Is it just binder changes?

**Comment by neobuddy89** [comment]
binder + sdcardfs

**Comment by gabrielgagz** [comment]
Hi can you reference wich commits did you use to ensure that nougat sources works on oreo?
I'm trying to port my kernel for pearlyn, wich is a twin device compared with shamu.
Thanks
